<?php
namespace Tests\Unit\Services;

use App\Services\LineBotService;
use Tests\TestCase;
class LineBotServiceTest extends TestCase
{
    /** @var  LineBotService */
    private $lineBotService;

    public function setUp():void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->lineBotService = app(LineBotService::class);
    }

    public function tearDown():void
    {
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testPushMessage()
    {

        $response = $this->lineBotService->pushMessage('Elliot現在沒空');

        $this->assertEquals(200, $response->getHTTPStatus());
    }
}